### ISSUE TITLE
Wybór oprogramowania

### ISSUE THREAD

**Issue by KanjoX** [ETIProjekt1gr2/Ekstraklasa.cba.pl#2]
Musimy najpierw ustalić z jakiego oprogramowania będziemy korzystać.
Proponuję wykonanie strony według tego szkicu:
![szkic_strony](https://cloud.githubusercontent.com/assets/11413360/6655991/70a8f586-cb18-11e4-98cd-beab955aa200.jpg)

**Comment by KanjoX** [comment]
Jako web master wybrałem program AptanaStudio

**Comment by SweetJameson** [comment]
Jako projektant baz danych wybieram program PowerDesigner.

**Comment by tympod123** [comment]
Gimp, jakieś pytania?
