### ISSUE TITLE
Projekt szaty graficznej

### ISSUE THREAD

**Issue by KanjoX** [ETIProjekt1gr2/Ekstraklasa.cba.pl#4]
18.03.2015r. do 25.04.2015r. Projekt szaty graficznej(wersja alfa)

**Comment by tympod123** [comment]
Kolejny projekt, tym razem całości strony głównej. Na tło nie zwracać uwagi, przez pomyłkę się czerwone zrobiło :P

https://github.com/ETIProjekt1gr2/Ekstraklasa.cba.pl/blob/master/strona%20g%C5%82%C3%B3wna%20projekt.jpg
