### ISSUE TITLE
Oczekiwanie na testowanie

### ISSUE THREAD

**Issue by KanjoX** [ETIProjekt1gr2/Ekstraklasa.cba.pl#6]
18.03.2015r. do 01.04.2015r. wybór przeglądarek do testów

**Comment by KanjoX** [comment]
Opóźnienie!!!!! termin przedłużam do 3.04.2015

**Comment by Hibiskustrzeci** [comment]
Do testów wybieram następujące przeglądarki:
- Internet Explorer 10
- Opera
- Mozilla Firefox
- Google Chrome
- Safari

**Comment by KanjoX** [comment]
Akceptacja
