### ISSUE TITLE
"Szkielet" bazy danych

### ISSUE THREAD

**Issue by KanjoX** [ETIProjekt1gr2/Ekstraklasa.cba.pl#8]
Wykonaj szkic Bazy danych  do 24.03.2015

**Comment by SweetJameson** [comment]
Pobrałem i Zainstalowałem oprogramowanie PowerDesigner.

**Comment by KanjoX** [comment]
Upomnienie!!!!!! termin przedłużam do 25.04.2015

**Comment by SweetJameson** [comment]
![pilkarze](https://cloud.githubusercontent.com/assets/11414148/7332800/1d2243e4-eb53-11e4-804f-88be3c665bea.png)

Raport z pracy. Uzupełnianie piłkarzy
